include:
  - board: seeeduino_xiao_ble
    shield: quickdraw_left
  - board: seeeduino_xiao_ble
    shield: quickdraw_right
  - board: seeeduino_xiao_ble
    shield: quickdraw_dongle
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset